### ISSUE TITLE
运行Demo，报了很多错误

### ISSUE THREAD

**Issue by zhoulijun12315** [xxxsimons/mpvue-vant#11]
![2018-09-19 6 30 37](https://user-images.githubusercontent.com/751744/45748067-3ea62100-bc3a-11e8-9c37-4544d3dfebdb.png)

不知道怎么解决

**Comment by xxxsimons** [comment]
@zhoulijun12315 仔细参照文档说明来，文档中有提到。 你这个问题是因为没开启小程序ES6转ES5功能。
