### ISSUE TITLE
popup组件会被map组件覆盖

### ISSUE THREAD

**Issue by xiaodel** [xxxsimons/mpvue-vant#13]
popup组件会被map组件覆盖，button不支持自定义背景颜色？

**Comment by xxxsimons** [comment]
1. map组件是原生组件，拥有最高层级。[小程序文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)

2. 可以参考这个[ youzan/vant-weapp#414](https://github.com/youzan/vant-weapp/issues/414)
