### ISSUE TITLE
使用tabs组件时报错

### ISSUE THREAD

**Issue by jerryachel** [xxxsimons/mpvue-vant#15]
Uncaught (in promise) TypeError: Cannot read property 'width' of undefined
    at index.js? [sm]:114
    at <anonymous>

报错的地方定位到tabs组件下的index.js文件里面的setLine()方法，this.getRect('.van-tab', true) 返回的rects是个空数组，然后就报错了

**Comment by xugongyang** [comment]
下载新版本试一下

**Comment by jerryachel** [comment]
> 
> 
> 下载新版本试一下

已经是9/19更新的新版本了，还是报错

**Comment by xugongyang** [comment]
tabs我之前也报错了 index.js 中 active类型改成了 Number

**Comment by xxxsimons** [comment]
能贴一下代码嘛？看报错好像你设置了`width`属性，但是文档好像没有`width`属性。贴一下代码吧！ @jerryachel

**Comment by jerryachel** [comment]
> 
> 
> 能贴一下代码嘛？看报错好像你设置了`width`属性，但是文档好像没有`width`属性。贴一下代码吧！ @jerryachel

`    <van-tabs  color="#d5b069" :active="activeTab" :line-width="48" @change="onTabChange">
      <van-tab title="待付款">待付款</van-tab>
      <van-tab title="待发货">待发货</van-tab>
      <van-tab title="已完成">已完成</van-tab>
    </van-tabs>`

源码的用意是获取tab标签的width以便设置底部的line-width，不是设置width，不过即使设不设置line-width都是报一样的错

**Comment by xxxsimons** [comment]
@jerryachel 我使用你的代码是没有报错的 ，可能你有什么地方配置不对，不知道你有没有打开微信开发者工具的ES6转ES5功能

**Comment by xxxsimons** [comment]
> 有打开ES6转ES5的
> 在vant-weapp里面也有类似的issue，应该算是vant-webapp的问题吧，看这里 [youzan/vant-weapp#671](https://github.com/youzan/vant-weapp/issues/671)

应该是的了 你可以下载最新的代码试试 今天刚更新了

**Comment by jerryachel** [comment]
> 
> 
> > 有打开ES6转ES5的
> > 在vant-weapp里面也有类似的issue，应该算是vant-webapp的问题吧，看这里 [youzan/vant-weapp#671](https://github.com/youzan/vant-weapp/issues/671)
> 
> 应该是的了 你可以下载最新的代码试试 今天刚更新了

好的，终于不报错了，十分感谢
