### ISSUE TITLE
妹子技术很不错，是在哪家公司工作

### ISSUE THREAD

**Issue by OrangeSnow** [xxxsimons/mpvue-vant#17]
我刚工作半年，学习小程序卡在一个点上了，虽然能跟着慕课的教程走完，但是感觉要往上一点就有些困难。

**Comment by xxxsimons** [comment]
其实我是男生，我大三还没工作呢。这种时候可以看看书吧，可以好好看看vue和阮一峰的ES6。我也是在学习的过程中总结了一些东西，怕以后忘了。

**Comment by OrangeSnow** [comment]
> 其实我是男生，我大三还没工作呢。这种时候可以看看书吧，可以好好看看vue和阮一峰的ES6。我也是在学习的过程中总结了一些东西，怕以后忘了。

你这头像太有欺骗性了，才大三就有这样的水平很厉害了，加油，接下来实习和校招很有望进bat
