### ISSUE TITLE
貌似无法正常使用action-sheet组件

### ISSUE THREAD

**Issue by leubao** [xxxsimons/mpvue-vant#19]
貌似无法正常使用action-sheet组件，无法传值

**Comment by xxxsimons** [comment]
代码贴一下

**Comment by leubao** [comment]
你试一下   我尝试了很多次都不行

**Comment by xxxsimons** [comment]
contactShow 这个值是什么，在哪里控制它的变化

**Comment by leubao** [comment]
非常感谢你的回复，contactShow默认值为false，当触发时改为true

**Comment by xxxsimons** [comment]
没事，大家一起踩坑。我测试过的，只要正确对照文档使用，基本是没问题的。周末还熬夜写代码，辛苦啊 @leubao

**Comment by leubao** [comment]
你能写个示例更新上来吗？我对照一下 看看我的错误在哪里 ？你还没睡呢

**Comment by leubao** [comment]
谢谢

**Comment by leubao** [comment]
试验了，使用mpvue-entry 后就不可以了。楼主可以试试

**Comment by webprevious** [comment]
你好，我这个引入就直接报错

**Comment by xxxsimons** [comment]
@webprevious 请描述清楚一些，引入啥报错，报啥错，代码贴上。

**Comment by webprevious** [comment]
ERROR  Failed to compile with 1 errors                                                                         16:49:18

 error  in ./src/pages/index/index.vue

(Emitted value instead of an instance of Error)
  Error compiling template:

  <div>小程序</div>
  <van-button>测试</van-button>

  - Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.


 @ ./src/pages/index/index.vue 10:0-368
 @ ./src/pages/index/main.js

**Comment by webprevious** [comment]
这个是npm run dev报错

**Comment by webprevious** [comment]
<template>
  <div>小程序</div>
  <van-button>测试</van-button>
</template>

<script>

export default {
  data () {
    return {
      
    }
  },

  components: {
    
  },

  methods: {
    
  },

  created () {
    
  }
}
</script>

<style scoped>

</style>

**Comment by webprevious** [comment]
`<template>
  <div>小程序</div>
  <van-button>测试</van-button>
</template>

<script>

export default {
  data () {
    return {
      
    }
  },

  components: {
    
  },

  methods: {
    
  },

  created () {
    
  }
}
</script>

<style scoped>

</style>
`

**Comment by webprevious** [comment]
{
    "usingComponents": {
        "van-button": "/static/vant/button/index"
    }
}

**Comment by webprevious** [comment]
这个是main.json里面的

**Comment by webprevious** [comment]
我是mpvue

**Comment by webprevious** [comment]
下载下来的组件全部放到static/vant里面了

**Comment by webprevious** [comment]
好的，不好意思

**Comment by webprevious** [comment]
你好，可以把一个mpvue项目引入了vant项目的代码给我看看吗

**Comment by xxxsimons** [comment]
@webprevious 仓库代码里的demo就是了

**Comment by webprevious** [comment]
thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export

**Comment by xxxsimons** [comment]
@webprevious 这个我是在文档中有提到，要打开微信开发者工具的`ES6转ES5`功能

**Comment by ifredom** [comment]
我这里是试用框架。直接引入 picker 和 ActionSheet 组件，picker正常使用，ActionSheet 组件报错找不到style文件

![image](https://user-images.githubusercontent.com/13759936/58147378-c3937f80-7c8c-11e9-8c18-cd5ab969310d.png)
![image](https://user-images.githubusercontent.com/13759936/58147406-e58d0200-7c8c-11e9-91dd-3aca6fdaf71c.png)
