### ISSUE TITLE
组件的custom-style没有效果

### ISSUE THREAD

**Issue by namezww** [xxxsimons/mpvue-vant#20]
我在使用icon组件用custom-style没有效果，官网已经新增了 custom-style 属性，不知道这个有没有新增？

**Comment by xxxsimons** [comment]
我测试了，是没有问题的，你对照看看是不是你哪里写错了。
@namezww 
[![未命名1539502138.png](https://i.loli.net/2018/10/14/5bc2f07963c5c.png)](https://i.loli.net/2018/10/14/5bc2f07963c5c.png)
[![未命名1539502147.png](https://i.loli.net/2018/10/14/5bc2f079590bb.png)](https://i.loli.net/2018/10/14/5bc2f079590bb.png)
[![未命名1539502154.png](https://i.loli.net/2018/10/14/5bc2f0795a8d1.png)](https://i.loli.net/2018/10/14/5bc2f0795a8d1.png)

**Comment by namezww** [comment]
![qq 20181019093931](https://user-images.githubusercontent.com/33592059/47192949-f423db80-d382-11e8-9a75-483a8a2a6d33.png)
![qq 20181019094027](https://user-images.githubusercontent.com/33592059/47192964-069e1500-d383-11e8-86af-a5c634925a3a.png)
我的还是不可以，是不是版本原因？

**Comment by xxxsimons** [comment]
你拉一下最新代码试试，或者用开发者工具选择器，看看是不是样式被覆盖了。

**Comment by namezww** [comment]
拉取最新的代码，已解决这个问题了，感谢感谢
