### ISSUE TITLE
使用icon时报无法加载.ttf错误

### ISSUE THREAD

**Issue by MarcWong** [xxxsimons/mpvue-vant#27]
在页面中引用了icon，图标可以正常加载，但报错无法加载字体，不知道有没有影响

``` html
 <van-icon name="after-sale" color="#f56250" size="20px" />
```

![image](https://user-images.githubusercontent.com/8611784/48425614-25d06c80-e7a0-11e8-8b44-5f74f0442b67.png)

**Comment by xxxsimons** [comment]
能正常使用就没啥影响，这应该是小程序开发者工具的问题。参考：[https://github.com/youzan/vant-weapp/issues/872#issuecomment-436542017](https://github.com/youzan/vant-weapp/issues/872#issuecomment-436542017)
