### ISSUE TITLE
static的vant下没有tabs只有tab

### ISSUE THREAD

**Issue by z20690865** [xxxsimons/mpvue-vant#8]
static的vant下没有tabs只有tab 忘记上传了吗

**Comment by xxxsimons** [comment]
代码更新只在vant目录下，demo里面的只是演示，没有更新

**Comment by z20690865** [comment]
vant目录下好像是原生的吧

**Comment by xxxsimons** [comment]
目前使用方法的都是使用原生组件。原生组件对slot支持比mpvue中的好

**Comment by z20690865** [comment]
直接用vant目录下的组件会报错jsEnginScriptError
Component is not found in path "vant/tabs/index" (using by "pages/index/main")
Error: Component is not found in path "vant/tabs/index" (using by "pages/index/main")

**Comment by xxxsimons** [comment]
你使用姿势不对，要把vant目录复制到你项目的static下面，通过/static/vant/...方式引入。如果你要用demo的话，用vant替换掉static目录下面的vant目录，看文档。 而且你那个引入的目录你注意看，你是用vant/tabs/index，那你看看你项目根目录下有vant目录吗？@z20690865

**Comment by z20690865** [comment]
还是报错啊thirdScriptError 
 sdk uncaught third Error 
 module "static/vant/common/create" is not defined 
 Error: module "static/vant/common/create" is not defined

**Comment by xxxsimons** [comment]
有报错你看看错误是啥呀，/static/vant/common/create 没找到这个文件，你到对应文件目录看看有没有，没有的话就是你没有把vant目录替换到/static/vant里面。 demo里面的代码不是最新的，我没更新里面的代码，我更新的是vant的代码。 @z20690865

**Comment by Escnt** [comment]
你好,我也遇到一样的问题了

**Comment by xxxsimons** [comment]
@Escnt 你打开微信开发者工具的ES6转ES5功能试试。

**Comment by z20690865** [comment]
确实有这个问题 按git clone下的原目录结构就没有问题 但如果把demo独立出来变成根目录就报这个错

**Comment by Escnt** [comment]
试了一下可以使用了,感谢回复

**Comment by z20690865** [comment]
确实打开es6转es5就可以了
